MATLAB binary installer update
bear-software/easybuild-easyblocks pull request #26
Opened 2020-05-06 11:36 UTC by orbsmiv

2020-05-07 08:35 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +from easybuild.tools.filetools import adjust_permissions, change_dir, read_file, write_file, remove_file
Ignoring

2020-05-07 08:43 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +        regkey = re.compile(r"^# fileInstallationKey=.*", re.M)
re.M is potentially dangerous here... since you end the expression with .*

2020-05-07 08:47 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +            os.close(fd)
This is dangerous here, as is only created in one particular code path. You can remove these two lines.

2020-05-07 08:49 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +                    fd, tmp_configfile = tempfile.mkstemp()
Better to do:

```
with tempfile.NamedTemporaryFile() as fd:
    tmp_configfile = fd.name
```

This gets cleaned up (and the file deleted) when you exit the `with` block.

2020-05-07 08:51 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +                    fd, tmp_configfile = tempfile.mkstemp()
Indeed, you could also do `tmp_config = fd.read()`

2020-05-07 08:53 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +                    fd, tmp_configfile = tempfile.mkstemp()
You would need to include this in the `with` block too:

```python
                    self.log.debug('temp config file written to %s:\n %s', tmp_configfile, tmp_config)
                    cmd = ' '.join([
                        self.cfg['preinstallopts'],
                        src,
                        '-inputFile',
                        tmp_configfile,
                        self.cfg['installopts'],
                    ])
                    (out, _) = run_cmd(cmd, log_all=True, simple=False)
```

Then move the duplicate final line into the else statement.

2020-05-07 08:54 UTC, edmondac requested changes
see comments

2020-05-07 09:04 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +        regkey = re.compile(r"^# fileInstallationKey=.*", re.M)
In fact, presumably since the system modules change, you can lose this line entirely now, and where it was used before just do:

```python
tmp_config = tmp_config.replace('# fileInstallationKey=', 'fileInstallationKey=%s' % key)
```

2020-05-07 14:45 UTC, orbsmiv commented on easybuild/easyblocks/m/matlab.py
> +            os.close(fd)
Removed

2020-05-07 14:45 UTC, orbsmiv commented on easybuild/easyblocks/m/matlab.py
> +                    fd, tmp_configfile = tempfile.mkstemp()
Applied with 22b1fd5

2020-05-07 14:46 UTC, orbsmiv commented on easybuild/easyblocks/m/matlab.py
> +        regkey = re.compile(r"^# fileInstallationKey=.*", re.M)
Applied with 22b1fd5

2020-05-11 08:22 UTC, edmondac approved these changes
lgtm

2020-05-11 08:24 UTC, merged