Matlab: remove non-ascii characters (Matlab 2020a)
bear-software/easybuild-easyblocks pull request #49
Opened 2020-11-14 11:12 UTC by afraz-ahmed

2020-11-16 16:55 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +            # remove non-ascii characters from installer_input.txt
I think you should move the preconfigopts command to this easyblock, and remove it from the easyconfig.

I.e. this section becomes:
```
if LooseVersion(self.version) >= LooseVersion('2020a'):
    # remove non-ascii characters from installer_input.txt
    cmd = 'LANG=C sed -i "s/[\d128-\d255]//g" installer_input.txt'
    run_cmd(cmd, log_all=True, simple=False)
```

2020-11-16 16:56 UTC, edmondac requested changes
See https://github.com/bear-rsg/easybuild-easyblocks/pull/49/files#r524420263

2020-11-16 16:58 UTC, orbsmiv commented on easybuild/easyblocks/m/matlab.py
> +            # remove non-ascii characters from installer_input.txt
@edmondac / @afraz-ahmed is this an issue specific to 2020a and above or does it occur due to running Easybuild with Python 3?

2020-11-16 17:30 UTC, afraz-ahmed commented on easybuild/easyblocks/m/matlab.py
> +            # remove non-ascii characters from installer_input.txt
It's a Python 3 issue, and the non-ascii character seems to be in previous Matlab versions as well, so I'll get rid of the if statement.

2020-11-16 17:46 UTC, afraz-ahmed commented on easybuild/easyblocks/m/matlab.py
> +            cmd = 'LANG=C sed -i "s/[\d128-\d255]//g" installer_input.txt'
this works...

2020-11-17 09:48 UTC, edmondac approved these changes
lgtm

2020-11-17 09:48 UTC, edmondac commented on easybuild/easyblocks/m/matlab.py
> +            # remove non-ascii characters from installer_input.txt
ok

2020-11-17 09:48 UTC, merged