STAR-CCM block
bear-software/easybuild-easyblocks pull request #86
Opened 2021-06-16 09:05 UTC by orbsmiv

2021-06-17 16:27 UTC, edmondac commented on easybuild/easyblocks/s/star_ccm.py
> +                )
I'd put both of these close brackets on line 83, after `self.version`

2021-06-17 16:28 UTC, edmondac commented on easybuild/easyblocks/s/star_ccm.py
> +            # Run the command, ignoring the exit code
You say "ignoring", but then you do things if ec!=0 . Perhaps "# Run the command, which may well have a non-zero exit code even though it has succeeded"

2021-06-17 16:29 UTC, edmondac commented on easybuild/easyblocks/s/star_ccm.py
> +            if ec != 0:
Is that really what you mean? Presumably if someone managed to get it to exit with 0, you would still want it to do what's in this block? In which case just remove the if and un-indent the block.

2021-06-17 16:31 UTC, edmondac commented on easybuild/easyblocks/s/star_ccm.py
> +                if self.starccm_subdir is None or self.starview_subdir is None:
```suggestion
                # The script may well have exited with non-fatal errors. We'll check.
                if self.starccm_subdir is None or self.starview_subdir is None:
```

2021-06-17 16:32 UTC, edmondac requested changes
see comments - mostly good though

2021-06-18 11:40 UTC, orbsmiv commented on easybuild/easyblocks/s/star_ccm.py
> +                )
Resolved by d6a27ee6

2021-06-18 11:42 UTC, orbsmiv commented on easybuild/easyblocks/s/star_ccm.py
> +            # Run the command, ignoring the exit code
Resolved in 7870d566

2021-06-18 16:18 UTC, edmondac approved these changes
lgtm

2021-06-18 16:18 UTC, merged